services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reportdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  phoenix:
    image: arizephoenix/phoenix:latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6006:6006" # UI & HTTP Collector
      - "4317:4317" # gRPC Collector
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres

volumes:
  postgres_data:
  qdrant_data:
